### ISSUE TITLE
Training Patches

### ISSUE THREAD

**Issue by hezhiquan** [FanChiMao/HWMNet#3]
Thank you for your excellent work. 
1.  May I ask how to get 4850 training patches?  Because LOL only has 485 data.
2.  How long does it take to train an epoch in the training process of LOL dataset ？
Looking forward to your reply. Thanks again.

**Comment by FanChiMao** [comment]
We use random crop 10 patches with the size of 256x256 for each image from LOL dataset by the code [generate_patches.py](https://github.com/FanChiMao/HWMNet/blob/main/generate_patches.py). 
As to training time, it cost about 14 minutes each epoch with batch size=2 via GTX 1080Ti.

**Comment by hezhiquan** [comment]
Thanks a lot!
