### ISSUE TITLE
Problem with events.out.tfevents file 

### ISSUE THREAD

**Issue by abetancordelrosario** [FanChiMao/HWMNet#7]
I want to visualize the training results using tensorboard but it fail when I execute the following command.

![imagen](https://user-images.githubusercontent.com/72502267/215431175-7847cce5-a540-4092-a9b6-c6ec95ab4b63.png)

Thank you in advance.

**Comment by FanChiMao** [comment]
the parameters of `--logdir` is the root of events.out.tfevents, so you should enter
```
tensorboard --logdir ./color/HWMNet/work-dir/HWMNet-96-LOL/log
```
or
```
tensorboard --logdir ./
```
in above case.
